### ISSUE TITLE
Did it can run 'Deterministic-v4' or 'NoFrameskip-v4'?

### ISSUE THREAD

**Issue by THSWind** [htdt/diqn#6]
Hello, 
Did it can run 'Deterministic-v4' or 'NoFrameskip-v4'? have you run other atari games, just like 'assault', 'breakout'. Does it has memory leak?

**Comment by htdt** [comment]
I tested it on `MsPacmanNoFrameskip-v4` and `SpaceInvadersNoFrameskip-v4`, but i think it will work on all the Atari suite. I didn't notice any memory leaks.
