### ISSUE TITLE
For Help: about how to operate replaybuffer?

### ISSUE THREAD

**Issue by THSWind** [htdt/diqn#7]
Hello, Alexander
Could you please tell me how to operate the replay buffer. Your code looks hard to read for me,  and it has less comment.
I want to get all of the memory(buffer) and operate, because of my work is to improve sample efficiency.

please help me, thank you very very much

**Comment by htdt** [comment]
The buffer is implemented here https://github.com/htdt/diqn/blob/master/core/buffer.py The logic is indeed complex, but I tried to keep the code clean and simple, most likely comments would not help. I recommend to go step by step on the functions to understand them. Also you can modify the buffer parameters in the configuration yaml.

**Comment by THSWind** [comment]
@htdt  Could you please just tell me how to get all of the elements of buffer, thus obs, reward, next_obs, reward, terminal?
 I have spent a lot of time on it. If you can help me, I'll appreciate it, because it save my time, plllz.  It's really hard to read for me

**Comment by THSWind** [comment]
At first, I was surprised at the neatness and rigor of the code, and then I was worried that it was really hard for me to understand

**Comment by htdt** [comment]
Sorry, i cannot assist in such detail. For this case I recommend to try popular implementation, e.g. https://github.com/google/dopamine
